title: Cody Wallace the Mechanical Engineer
description: > # this means to ignore newlines until "baseurl:"
  Cody Wallace is a Mechanical Engineer with a focus in R&D and Manufacturing. My goal: to bring a product from concept to reality in the best way possible. 
permalink: ':title/'
baseurl: "/Portfolio/" # the subpath of your site, e.g. /blog
url: "https://codywallace245.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Cody Wallace # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am a Mechanical Engineer working as a Manufacturing Engineer at <a href="https://formlabs.com/"> Formlabs </a>.<br> # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: CodyWallace245 # add your Github handle
linkedin: cody-wallace-21018864 # add your Linkedin handle
email: cody.wallace245@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
